### ISSUE TITLE
Magento 2.4: «Argument 1 passed to Df\Core\State::controllerSet() must be an instance of Magento\Framework\App\Action\Action, instance of Magento\Framework\App\Action\Forward\Interceptor given, called in endor/mage2pro/core/Core/Observer/ControllerActionPredispatch.php on line 16»

### ISSUE THREAD

**Issue by jaxtheking** [mage2pro/core#108]
I've just upgraded to Magento 2.4.0 and I'm getting the following error on any catalogue page:
```
TypeError: Argument 1 passed to Df\Core\State::controllerSet() must be an instance of Magento\Framework\App\Action\Action, instance of Magento\Framework\App\Action\Forward\Interceptor given, called in /public_html/dev/vendor/mage2pro/core/Core/Observer/ControllerActionPredispatch.php on line 16 and defined in /public_html/dev/vendor/mage2pro/core/Core/State.php:107
```

Has anyone experienced this issue?

**Comment by dmitry-fedyuk** [comment]
You can hire me in Upwork to analyze and solve it: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)

**Comment by jaxtheking** [comment]
Should you had asserted before your offer that it did likely depend on my setup and not the module being outdate, then I might have taken you up.
I'll just do without the module - but thanks anyways.
