### ISSUE TITLE
A consecutive call of the «GET» and «PUT» REST API methods for the same customer leads to the «Error occurred during "custom_attributes" processing. Value is not set for attribute code "df"» failure

### ISSUE THREAD

**Issue by astintzing** [mage2pro/core#12]
Hi,

I'm currently testing the stripe payment extension and it depends on the core extension. 

We are heavily using the rest api and since installing the module (by composer), a new attribute called "df" is needed to be set. This attribute is added in /vendor/mage2pro/core/Customer/Setup/UpgradeSchema.php
And yes, it's not required per definition/configuration, but on fetching a customer by the call 

`GET index.php/rest/all/V1/customers/<id>`

then the custom_attributes of the response having an item with value=NULL, attribute_code="df".

So, on saving the same data by calling

`PUT index.php/rest/all/V1/customers/<id>`

an exception is thrown:

`Error occurred during \"custom_attributes\" processing. Value is not set for attribute code \"df\"`

So this breaks at this point. The normal behavior is: If a custom_attribute is not set, this will not be shown in the custom_attributes.

As a workaround it is possible to delete the item or set the value to an empty string, but it's a workaround and not the default behavior.

Response of the GET call formatted as array and returned with var_dump:
<pre>
array(14) {
  ["id"]=>
  int(2)
  ["group_id"]=>
  int(1)
  ["created_at"]=>
  string(19) "2017-05-09 23:25:16"
  ["updated_at"]=>
  string(19) "2017-06-16 19:16:18"
  ["created_in"]=>
  string(11) "Österreich"
  ["email"]=>
  string(22) "alex@stintzing.net"
  ["firstname"]=>
  string(4) "Kumm"
  ["lastname"]=>
  string(4) "Scho"
  ["middlename"]=>
  string(4) "Paul"
  ["store_id"]=>
  int(1)
  ["website_id"]=>
  int(1)
  ["addresses"]=>
  array(0) {
  }
  ["disable_auto_group_change"]=>
  int(0)
  ["custom_attributes"]=>
  array(1) {
    [0]=>
    array(2) {
      ["attribute_code"]=>
      string(2) "df"
      ["value"]=>
      NULL
    }
  }
}
</pre>

**To get this tailored:** 

On calling the PUT and removing the item with attribute_code="df" the next GET will return  custom_attributes containing the previous deleted item again. This is added somewhere on the fly you will better know as I do.

My test is using guzzlehttp/guzzle and zendframework/zend-json as composer dependency. The custom_attribute "fundi_id" is use to see the normal behavior, this is the corresponding id of the erp system of my customer:

<pre>

&lt;?php

include 'vendor/autoload.php';

$baseProtocolAndDomain = "http://example.com/";

$baseUrl = "index.php/rest/all/V1/";
$baseUrl = $baseProtocolAndDomain . $baseUrl;

$client = new GuzzleHttp\Client();

$token = NULL;

if (! $token) {

    $response = $client->post($baseUrl . 'integration/admin/token/', [
        "json" => [
           "username" => "username",
           "password" => "password"
        ]
    ]);
    
    $token = Zend\Json\Json::decode($response->getBody());
}

$params['headers']["Authorization"] = 'Bearer' . ' ' . $token;

$response = $client->get($baseUrl . 'customers/2', $params);

// this response does have the attribute set
var_dump(Zend\Json\Json::decode($response->getBody()));

$customer = Zend\Json\Json::decode($response->getBody(), Zend\Json\Json::TYPE_ARRAY);

$fundiIdSet = FALSE;

foreach($customer['custom_attributes'] as $id => $att) {
    if ($att['attribute_code'] == 'df' && $att['value'] === NULL) {
        // works, that's the current workaround
        unset($customer['custom_attributes'][$id]);
        // would also work:
        //$att['value'] = '';
    }
    
    if ($att['attribute_code'] == 'fundi_id') {
        $fundiIdSet = TRUE;
    }
}

if (! $fundiIdSet) {
    $customer['custom_attributes'][] = ["attribute_code" => 'fundi_id', "value" => 'test123'];
}

$customer["middlename"] = 'Paul';

$params['json'] = ['customer' => $customer];

$response = $client->put($baseUrl . 'customers/2', $params);
// this response does not have the custom attribute set
var_dump(Zend\Json\Json::decode($response->getBody()));

$response = $client->get($baseUrl . 'customers/2', $params);
// and this response does have the custom attribute set again
var_dump(Zend\Json\Json::decode($response->getBody()));
</pre>

Greetings from Berlin to Moscow!

Alex

**Comment by dmitry-fedyuk** [comment]
Learn how to pay for my extensions before spending my time.

**Comment by astintzing** [comment]
Sorry,

I don't use your software without paying. I asked you directly if it's possible to use that in a development environment 2 days ago - your answer was one word "yes". I told my customer better to use your extension because it's easily available by composer. 
The system is not public, and the few money your module costs won't be payed by me but by my customer. There is no sense for me not paying for your work.

With this bugreport I don't want to blame you but make your module better. My case is not the default case but if your module fits even this case is will be more robust. I spent a lot of time to write this bugreport and did many tests to be sure not saying shit.

I sent 2 seconds ago 99$ to your paypal account admin@mage2.pro.

Please open the Ticket again, I trust your work and I am not a highwayman robbing you out. Your Code is clean, that's why I'm writing.

Good night.

**Comment by dmitry-fedyuk** [comment]
OK, thanks for purchasing the extension.
I will check the problem.

**Comment by dmitry-fedyuk** [comment]
I have investigated the issue.  
It is by Magento 2 design: [The Magento 2 REST API forbids the `null` value for an entity's custom attribute in a `PUT` request](https://mage2.pro/t/topic/4072).  
Magento 2 team intentionally designed it so.  
I do not think it is a good decision, but it exists, and you need to use a workaround.  
It is not related to the `mage2pro/core` package, nor to the Mage2.PRO extensions: you will get the same error for any custom attribute with the `null` value.  
A good workaround is to use the [`array_filter`](http://php.net/manual/en/function.array-filter.php) function with a callback, which removes all the `null`-valued attributes before a REST API request:

```
use Magento\Framework\Api\AttributeInterface as IAttribute;
use Magento\Framework\Api\CustomAttributesDataInterface as ICAD;
<...>
$customer[ICAD::CUSTOM_ATTRIBUTES] = array_filter($customer[ICAD::CUSTOM_ATTRIBUTES], function($a) {return
    !isset($a[IAttribute::VALUE])
;});
```  
I recommend also ask the Magento 2 team why did they design it so.
