### ISSUE TITLE
«Argument 1 passed to df_path_is_internal() must be of the type string, null given, called in vendor/mage2pro/core/Framework/Plugin/Session/SessionManager.php on line 50»

### ISSUE THREAD

**Issue by AlaaL** [mage2pro/core#226]
Hello,

When installing the plugin in Magento 2.3 using composer and then executing `bin\magento setup:upgrade` i get this error message:

`Type Error occurred when creating object: Magento\Backend\Model\Session\Interceptor, Argument 1 passed to df_path_is_internal() must be of the type string, null given, called in /home/lelasnet/public_html/vendor/mage2pro/core/Framework/Plugin/Session/SessionManager.php on line 50`

**Comment by dmitrii-fediuk** [comment]
Fixed.
