### ISSUE TITLE
The Mage2.PRO payment modules show the «Please agree to all the terms and conditions before placing the order» warning in Magento 2.2 and 2.3 even if the terms and conditions checkbox is checked

### ISSUE THREAD

**Issue by dmitry-fedyuk** [mage2pro/core#65]
https://github.com/mage2pro/ipay88/issues/7

**Comment by dmitry-fedyuk** [comment]
Fixed in [3.6.0](https://github.com/mage2pro/core/releases/tag/3.6.0).

**Comment by topranavp** [comment]
same issue with Payumoney module. Here is the link for the extension. https://github.com/payu-india/PayUbiz_Magento/tree/ver2.x

Can you share the fix?

**Comment by dmitry-fedyuk** [comment]
I can implement the same fix for the Payumoney module for **$150**.
