### ISSUE TITLE
issue on admin report page 

### ISSUE THREAD

**Issue by chirag-taraviya** [mage2pro/core#74]
issue notice at: mage2pro\core\Framework\Plugin\Data\Form\Element\AbstractElement.php

line141: remove ', ' from class

it mashup layout of admin side report panel.
![report_layout](https://user-images.githubusercontent.com/531597/38291930-6dd49944-37ff-11e8-91ef-ad00bfc5e4c6.PNG)

**Comment by dmitry-fedyuk** [comment]
Your pull request is merged in [3.6.18](https://github.com/mage2pro/core/releases/tag/3.6.18).
