### ISSUE TITLE
Update `freegeoip.net` to `freegeoip.app`

### ISSUE THREAD

**Issue by dmitry-fedyuk** [mage2pro/core#76]
https://github.com/apilayer/freegeoip/tree/v3.5.0#readme

**Comment by freegeoipapp** [comment]
I've setup
https://freegeoip.app

- HTTPS (no HTTP, sorry - it's 2018)
- Rate limit of 15000/hour as before for FREE, guaranteed
- No logs, no analytics - privacy alway in mind

It's the same api - just a different TLD ;) let me know if you have any problems integrating.

**Comment by dmitry-fedyuk** [comment]
Implemented in [3.7.30](https://github.com/mage2pro/core/releases/tag/3.7.30).

**Comment by dmitry-fedyuk** [comment]
https://github.com/mage2pro/core/issues/87
